### ISSUE TITLE
Crash on Instagram video

### ISSUE THREAD

**Issue by PlkMarudny** [arutkowski00/VIDEOwnloader#5]
The following url [https://www.instagram.com/p/BOAls5SAFru/?taken-by=fun_bestvids](https://www.instagram.com/p/BOAls5SAFru/?taken-by=fun_bestvids) causes a crash in a NewDownloadViewModel.cs in line 88; Formats property returned is null, thus crash happens.

Call stack shows:

>	VIDEOwnloader.exe!VIDEOwnloader.ViewModel.NewDownloadViewModel.AvailableFormats.get() Line 88	C#

**Comment by arutkowski00** [comment]
It looks like updating youtube-dl binary to 2016.12.22 (newest) solves this problem.

Fixed in b115e54
